services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: sic
      POSTGRES_USER: sicdbadmin
      POSTGRES_PASSWORD: 123456
    volumes:
      - ../docker-compose/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sicdbadmin"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kcsecret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  vault:
    image: hashicorp/vault:1.13
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: vault server -dev
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/data

  vault-init:
    image: alpine:3.19
    container_name: vault-init
    depends_on:
      - vault
    entrypoint: /bin/sh
    command: -c "/vault/vault-secrets.sh"
    volumes:
      - ./vault-secrets.sh:/vault/vault-secrets.sh
  keycloak-init:
    build:
      context: .
      dockerfile: Dockerfile.keycloak-init
    container_name: keycloak-init
    depends_on:
      - keycloak
    volumes:
      - ./keycloak-init.sh:/init/keycloak-init.sh
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin123
      - KEYCLOAK_HOST=http://keycloak:8080
  backend:
    build:
      context: ../SicBackend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
      - vault
      - keycloak
    ports:
      - "8081:8081"
  frontend:
    build:
      context: ../web-sic
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - keycloak

volumes:
  vault-data:
