FROM alpine:3.19

# Instala curl y jq
RUN apk add --no-cache curl jq

# Copia el script de inicialización
COPY keycloak-init.sh /init/keycloak-init.sh

# Da permisos de ejecución
RUN chmod +x /init/keycloak-init.sh

# Ejecuta el script
ENTRYPOINT ["/init/keycloak-init.sh"]
